### ISSUE TITLE
Option to disable/enable ligatures

### ISSUE THREAD

**Issue by Inclushe** [nobuhito/vscode.printcode#18]
I had to go into Chrome Devtools to insert one line of CSS to remove the ligatures from my coding font so that my professor doesn't go "wtf are these symbols".
I feel like it would be better as a configuration option instead of having to manually set it each time.

[](https://developer.mozilla.org/en-US/docs/Web/CSS/font-variant-ligatures)

**Comment by janilahti** [comment]
Could you include your CSS snipplet here?

**Comment by Inclushe** [comment]
This is what I used:
```css
.cm-s-default .cm-variable, .cm-s-default .cm-punctuation, .cm-s-default .cm-property, .cm-s-default .cm-operator {
    font-variant-ligatures: none;
}
```
Perhaps it could be added as a configuration option with the settings `on`, `off`, or `auto`, with `auto` defaulting to the `editor.fontLigatures` user setting.
